apiVersion: v1
kind: Service
metadata:
  name: testlink
  labels:
    app: testlink
  namespace: testlink
spec:
  type: NodePort
  selector:
    app: testlink
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
