apiVersion: apps/v1
kind: Deployment
metadata:
  name: testlink
  labels:
    app: teslink
  namespace: testlink
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testlink
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: testlink
        tier: frontend
    spec:
      containers:
      - image: bitnami/testlink:1.9.16
        name: testlink
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: yes
        - name: TESTLINK_DB_USER
          value: bn_testlink
        - name: TESTLINK_DB_NAME
          value: bitnami_testlink
        - name: testlink_DB_PASSWORD
          value: bitnami
        ports:
        - containerPort: 80
          name: testlink
        volumeMounts:
        - name: testlink_data
          mountPath: /home/testplan
      volumes:
      - name: testlink_data
        hostPath:
          path: /bitnami/testlink
      depend_on:
        - mariadb
